### PR TITLE
update cmake file for python 3.12 on ubuntu 22 with system python being 3.10

### PR DESCRIPTION
**Pull request by le-horizon**
Tested, this works on ubuntu 22 with python 3.12.
Andrew, could you test on your ubuntu 24?

Requires Hobot side change to build_rapid_env.py.

I'll try to test it on ubuntu 22 with python3.10 as well.

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -1,31 +1,31 @@
...
+endif()
+set(CMAKE_CXX_FLAGS_RELEASE "-O3")
 
-set(CMAKE_CXX_FLAGS "-O3 -DNDEBUG -Wno-deprecated-declarations")
+message(STATUS "Using compiler ${CMAKE_CXX_COMPILER_ID} ...")
 
-find_package(Python3 REQUIRED COMPONENTS Interpreter Development)
-find_package(pybind11 REQUIRED)
+find_package(pybind11 CONFIG REQUIRED)
+find_package(Python3 3.12 REQUIRED COMPONENTS Interpreter Development)
```
Comment (QuantuMope) [inline CMakeLists.txt:12]: Instead of hardcoding python 3.12 here, should we add a cmake arg so user can choose?

**Review by QuantuMope — COMMENTED** [review]
Hey Le,

On Ubuntu 24.04, I am now getting this error

```
In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/utils.h:3,
                 from /home/asjchoi/Desktop/Code/kincpp/src/utils.cpp:1:
/home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
    3 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/kinematics_solver.h:3,
                 from /home/asjchoi/Desktop/Code/kincpp/src/kinematics_solver.cpp:1:
/home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
    3 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
compilation terminated.
compilation terminated.
make[2]: *** [CMakeFiles/kincpp.dir/build.make:90: CMakeFiles/kincpp.dir/src/utils.cpp.o] Error 1
```

Can confirm that build works on `main`.

**Comment by le-horizon** [comment]
> Hey Le,
> 
> On Ubuntu 24.04, I am now getting this error
> 
> ```
> In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/utils.h:3,
>                  from /home/asjchoi/Desktop/Code/kincpp/src/utils.cpp:1:
> /home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
>     3 | #include <Eigen/Dense>
>       |          ^~~~~~~~~~~~~
> In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/kinematics_solver.h:3,
>                  from /home/asjchoi/Desktop/Code/kincpp/src/kinematics_solver.cpp:1:
> /home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
>     3 | #include <Eigen/Dense>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> compilation terminated.
> make[2]: *** [CMakeFiles/kincpp.dir/build.make:90: CMakeFiles/kincpp.dir/src/utils.cpp.o] Error 1
> ```
> 
> Can confirm that build works on `main`.

Ah, not as easy as I thought..  Could you give me access to your env so I can test?

Re: hardcoding 3.12, I'm thinking probably choose based on virtualenv.  But let me debug this 312 version first.

**Comment by QuantuMope** [comment]
> > Hey Le,
> > On Ubuntu 24.04, I am now getting this error
> > ```
> > In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/utils.h:3,
> >                  from /home/asjchoi/Desktop/Code/kincpp/src/utils.cpp:1:
> > /home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
> >     3 | #include <Eigen/Dense>
> >       |          ^~~~~~~~~~~~~
> > In file included from /home/asjchoi/Desktop/Code/kincpp/src/kincpp/kinematics_solver.h:3,
> >                  from /home/asjchoi/Desktop/Code/kincpp/src/kinematics_solver.cpp:1:
> > /home/asjchoi/Desktop/Code/kincpp/src/kincpp/global_definitions.h:3:10: fatal error: Eigen/Dense: No such file or directory
> >     3 | #include <Eigen/Dense>
> >       |          ^~~~~~~~~~~~~
> > compilation terminated.
> > compilation terminated.
> > make[2]: *** [CMakeFiles/kincpp.dir/build.make:90: CMakeFiles/kincpp.dir/src/utils.cpp.o] Error 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can confirm that build works on `main`.
> 
> Ah, not as easy as I thought.. Could you give me access to your env so I can test?
> 
> Re: hardcoding 3.12, I'm thinking probably choose based on virtualenv. But let me debug this 312 version first.

I run Ubuntu 24.04 on my home computer. Work computer is 22.04 unfortunately.
